/*  PCSX2 - PS2 Emulator for PCs
 *  Copyright (C) 2002-2020  PCSX2 Dev Team
 *
 *  PCSX2 is free software: you can redistribute it and/or modify it under the terms
 *  of the GNU Lesser General Public License as published by the Free Software Found-
 *  ation, either version 3 of the License, or (at your option) any later version.
 *
 *  PCSX2 is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with PCSX2.
 *  If not, see <http://www.gnu.org/licenses/>.
 */

#include "input-keymap-linux-to-qcode.h"
const QKeyCode qemu_input_map_linux_to_qcode[] = {
	Q_KEY_CODE_UNMAPPED,         /* linux:0 (KEY_RESERVED) -> linux:0 (KEY_RESERVED) -> qcode:Q_KEY_CODE_UNMAPPED (unmapped) */
	Q_KEY_CODE_ESC,              /* linux:1 (KEY_ESC) -> linux:1 (KEY_ESC) -> qcode:Q_KEY_CODE_ESC (esc) */
	Q_KEY_CODE_1,                /* linux:2 (KEY_1) -> linux:2 (KEY_1) -> qcode:Q_KEY_CODE_1 (1) */
	Q_KEY_CODE_2,                /* linux:3 (KEY_2) -> linux:3 (KEY_2) -> qcode:Q_KEY_CODE_2 (2) */
	Q_KEY_CODE_3,                /* linux:4 (KEY_3) -> linux:4 (KEY_3) -> qcode:Q_KEY_CODE_3 (3) */
	Q_KEY_CODE_4,                /* linux:5 (KEY_4) -> linux:5 (KEY_4) -> qcode:Q_KEY_CODE_4 (4) */
	Q_KEY_CODE_5,                /* linux:6 (KEY_5) -> linux:6 (KEY_5) -> qcode:Q_KEY_CODE_5 (5) */
	Q_KEY_CODE_6,                /* linux:7 (KEY_6) -> linux:7 (KEY_6) -> qcode:Q_KEY_CODE_6 (6) */
	Q_KEY_CODE_7,                /* linux:8 (KEY_7) -> linux:8 (KEY_7) -> qcode:Q_KEY_CODE_7 (7) */
	Q_KEY_CODE_8,                /* linux:9 (KEY_8) -> linux:9 (KEY_8) -> qcode:Q_KEY_CODE_8 (8) */
	Q_KEY_CODE_9,                /* linux:10 (KEY_9) -> linux:10 (KEY_9) -> qcode:Q_KEY_CODE_9 (9) */
	Q_KEY_CODE_0,                /* linux:11 (KEY_0) -> linux:11 (KEY_0) -> qcode:Q_KEY_CODE_0 (0) */
	Q_KEY_CODE_MINUS,            /* linux:12 (KEY_MINUS) -> linux:12 (KEY_MINUS) -> qcode:Q_KEY_CODE_MINUS (minus) */
	Q_KEY_CODE_EQUAL,            /* linux:13 (KEY_EQUAL) -> linux:13 (KEY_EQUAL) -> qcode:Q_KEY_CODE_EQUAL (equal) */
	Q_KEY_CODE_BACKSPACE,        /* linux:14 (KEY_BACKSPACE) -> linux:14 (KEY_BACKSPACE) -> qcode:Q_KEY_CODE_BACKSPACE (backspace) */
	Q_KEY_CODE_TAB,              /* linux:15 (KEY_TAB) -> linux:15 (KEY_TAB) -> qcode:Q_KEY_CODE_TAB (tab) */
	Q_KEY_CODE_Q,                /* linux:16 (KEY_Q) -> linux:16 (KEY_Q) -> qcode:Q_KEY_CODE_Q (q) */
	Q_KEY_CODE_W,                /* linux:17 (KEY_W) -> linux:17 (KEY_W) -> qcode:Q_KEY_CODE_W (w) */
	Q_KEY_CODE_E,                /* linux:18 (KEY_E) -> linux:18 (KEY_E) -> qcode:Q_KEY_CODE_E (e) */
	Q_KEY_CODE_R,                /* linux:19 (KEY_R) -> linux:19 (KEY_R) -> qcode:Q_KEY_CODE_R (r) */
	Q_KEY_CODE_T,                /* linux:20 (KEY_T) -> linux:20 (KEY_T) -> qcode:Q_KEY_CODE_T (t) */
	Q_KEY_CODE_Y,                /* linux:21 (KEY_Y) -> linux:21 (KEY_Y) -> qcode:Q_KEY_CODE_Y (y) */
	Q_KEY_CODE_U,                /* linux:22 (KEY_U) -> linux:22 (KEY_U) -> qcode:Q_KEY_CODE_U (u) */
	Q_KEY_CODE_I,                /* linux:23 (KEY_I) -> linux:23 (KEY_I) -> qcode:Q_KEY_CODE_I (i) */
	Q_KEY_CODE_O,                /* linux:24 (KEY_O) -> linux:24 (KEY_O) -> qcode:Q_KEY_CODE_O (o) */
	Q_KEY_CODE_P,                /* linux:25 (KEY_P) -> linux:25 (KEY_P) -> qcode:Q_KEY_CODE_P (p) */
	Q_KEY_CODE_BRACKET_LEFT,     /* linux:26 (KEY_LEFTBRACE) -> linux:26 (KEY_LEFTBRACE) -> qcode:Q_KEY_CODE_BRACKET_LEFT (bracket_left) */
	Q_KEY_CODE_BRACKET_RIGHT,    /* linux:27 (KEY_RIGHTBRACE) -> linux:27 (KEY_RIGHTBRACE) -> qcode:Q_KEY_CODE_BRACKET_RIGHT (bracket_right) */
	Q_KEY_CODE_RET,              /* linux:28 (KEY_ENTER) -> linux:28 (KEY_ENTER) -> qcode:Q_KEY_CODE_RET (ret) */
	Q_KEY_CODE_CTRL,             /* linux:29 (KEY_LEFTCTRL) -> linux:29 (KEY_LEFTCTRL) -> qcode:Q_KEY_CODE_CTRL (ctrl) */
	Q_KEY_CODE_A,                /* linux:30 (KEY_A) -> linux:30 (KEY_A) -> qcode:Q_KEY_CODE_A (a) */
	Q_KEY_CODE_S,                /* linux:31 (KEY_S) -> linux:31 (KEY_S) -> qcode:Q_KEY_CODE_S (s) */
	Q_KEY_CODE_D,                /* linux:32 (KEY_D) -> linux:32 (KEY_D) -> qcode:Q_KEY_CODE_D (d) */
	Q_KEY_CODE_F,                /* linux:33 (KEY_F) -> linux:33 (KEY_F) -> qcode:Q_KEY_CODE_F (f) */
	Q_KEY_CODE_G,                /* linux:34 (KEY_G) -> linux:34 (KEY_G) -> qcode:Q_KEY_CODE_G (g) */
	Q_KEY_CODE_H,                /* linux:35 (KEY_H) -> linux:35 (KEY_H) -> qcode:Q_KEY_CODE_H (h) */
	Q_KEY_CODE_J,                /* linux:36 (KEY_J) -> linux:36 (KEY_J) -> qcode:Q_KEY_CODE_J (j) */
	Q_KEY_CODE_K,                /* linux:37 (KEY_K) -> linux:37 (KEY_K) -> qcode:Q_KEY_CODE_K (k) */
	Q_KEY_CODE_L,                /* linux:38 (KEY_L) -> linux:38 (KEY_L) -> qcode:Q_KEY_CODE_L (l) */
	Q_KEY_CODE_SEMICOLON,        /* linux:39 (KEY_SEMICOLON) -> linux:39 (KEY_SEMICOLON) -> qcode:Q_KEY_CODE_SEMICOLON (semicolon) */
	Q_KEY_CODE_APOSTROPHE,       /* linux:40 (KEY_APOSTROPHE) -> linux:40 (KEY_APOSTROPHE) -> qcode:Q_KEY_CODE_APOSTROPHE (apostrophe) */
	Q_KEY_CODE_GRAVE_ACCENT,     /* linux:41 (KEY_GRAVE) -> linux:41 (KEY_GRAVE) -> qcode:Q_KEY_CODE_GRAVE_ACCENT (grave_accent) */
	Q_KEY_CODE_SHIFT,            /* linux:42 (KEY_LEFTSHIFT) -> linux:42 (KEY_LEFTSHIFT) -> qcode:Q_KEY_CODE_SHIFT (shift) */
	Q_KEY_CODE_BACKSLASH,        /* linux:43 (KEY_BACKSLASH) -> linux:43 (KEY_BACKSLASH) -> qcode:Q_KEY_CODE_BACKSLASH (backslash) */
	Q_KEY_CODE_Z,                /* linux:44 (KEY_Z) -> linux:44 (KEY_Z) -> qcode:Q_KEY_CODE_Z (z) */
	Q_KEY_CODE_X,                /* linux:45 (KEY_X) -> linux:45 (KEY_X) -> qcode:Q_KEY_CODE_X (x) */
	Q_KEY_CODE_C,                /* linux:46 (KEY_C) -> linux:46 (KEY_C) -> qcode:Q_KEY_CODE_C (c) */
	Q_KEY_CODE_V,                /* linux:47 (KEY_V) -> linux:47 (KEY_V) -> qcode:Q_KEY_CODE_V (v) */
	Q_KEY_CODE_B,                /* linux:48 (KEY_B) -> linux:48 (KEY_B) -> qcode:Q_KEY_CODE_B (b) */
	Q_KEY_CODE_N,                /* linux:49 (KEY_N) -> linux:49 (KEY_N) -> qcode:Q_KEY_CODE_N (n) */
	Q_KEY_CODE_M,                /* linux:50 (KEY_M) -> linux:50 (KEY_M) -> qcode:Q_KEY_CODE_M (m) */
	Q_KEY_CODE_COMMA,            /* linux:51 (KEY_COMMA) -> linux:51 (KEY_COMMA) -> qcode:Q_KEY_CODE_COMMA (comma) */
	Q_KEY_CODE_DOT,              /* linux:52 (KEY_DOT) -> linux:52 (KEY_DOT) -> qcode:Q_KEY_CODE_DOT (dot) */
	Q_KEY_CODE_SLASH,            /* linux:53 (KEY_SLASH) -> linux:53 (KEY_SLASH) -> qcode:Q_KEY_CODE_SLASH (slash) */
	Q_KEY_CODE_SHIFT_R,          /* linux:54 (KEY_RIGHTSHIFT) -> linux:54 (KEY_RIGHTSHIFT) -> qcode:Q_KEY_CODE_SHIFT_R (shift_r) */
	Q_KEY_CODE_KP_MULTIPLY,      /* linux:55 (KEY_KPASTERISK) -> linux:55 (KEY_KPASTERISK) -> qcode:Q_KEY_CODE_KP_MULTIPLY (kp_multiply) */
	Q_KEY_CODE_ALT,              /* linux:56 (KEY_LEFTALT) -> linux:56 (KEY_LEFTALT) -> qcode:Q_KEY_CODE_ALT (alt) */
	Q_KEY_CODE_SPC,              /* linux:57 (KEY_SPACE) -> linux:57 (KEY_SPACE) -> qcode:Q_KEY_CODE_SPC (spc) */
	Q_KEY_CODE_CAPS_LOCK,        /* linux:58 (KEY_CAPSLOCK) -> linux:58 (KEY_CAPSLOCK) -> qcode:Q_KEY_CODE_CAPS_LOCK (caps_lock) */
	Q_KEY_CODE_F1,               /* linux:59 (KEY_F1) -> linux:59 (KEY_F1) -> qcode:Q_KEY_CODE_F1 (f1) */
	Q_KEY_CODE_F2,               /* linux:60 (KEY_F2) -> linux:60 (KEY_F2) -> qcode:Q_KEY_CODE_F2 (f2) */
	Q_KEY_CODE_F3,               /* linux:61 (KEY_F3) -> linux:61 (KEY_F3) -> qcode:Q_KEY_CODE_F3 (f3) */
	Q_KEY_CODE_F4,               /* linux:62 (KEY_F4) -> linux:62 (KEY_F4) -> qcode:Q_KEY_CODE_F4 (f4) */
	Q_KEY_CODE_F5,               /* linux:63 (KEY_F5) -> linux:63 (KEY_F5) -> qcode:Q_KEY_CODE_F5 (f5) */
	Q_KEY_CODE_F6,               /* linux:64 (KEY_F6) -> linux:64 (KEY_F6) -> qcode:Q_KEY_CODE_F6 (f6) */
	Q_KEY_CODE_F7,               /* linux:65 (KEY_F7) -> linux:65 (KEY_F7) -> qcode:Q_KEY_CODE_F7 (f7) */
	Q_KEY_CODE_F8,               /* linux:66 (KEY_F8) -> linux:66 (KEY_F8) -> qcode:Q_KEY_CODE_F8 (f8) */
	Q_KEY_CODE_F9,               /* linux:67 (KEY_F9) -> linux:67 (KEY_F9) -> qcode:Q_KEY_CODE_F9 (f9) */
	Q_KEY_CODE_F10,              /* linux:68 (KEY_F10) -> linux:68 (KEY_F10) -> qcode:Q_KEY_CODE_F10 (f10) */
	Q_KEY_CODE_NUM_LOCK,         /* linux:69 (KEY_NUMLOCK) -> linux:69 (KEY_NUMLOCK) -> qcode:Q_KEY_CODE_NUM_LOCK (num_lock) */
	Q_KEY_CODE_SCROLL_LOCK,      /* linux:70 (KEY_SCROLLLOCK) -> linux:70 (KEY_SCROLLLOCK) -> qcode:Q_KEY_CODE_SCROLL_LOCK (scroll_lock) */
	Q_KEY_CODE_KP_7,             /* linux:71 (KEY_KP7) -> linux:71 (KEY_KP7) -> qcode:Q_KEY_CODE_KP_7 (kp_7) */
	Q_KEY_CODE_KP_8,             /* linux:72 (KEY_KP8) -> linux:72 (KEY_KP8) -> qcode:Q_KEY_CODE_KP_8 (kp_8) */
	Q_KEY_CODE_KP_9,             /* linux:73 (KEY_KP9) -> linux:73 (KEY_KP9) -> qcode:Q_KEY_CODE_KP_9 (kp_9) */
	Q_KEY_CODE_KP_SUBTRACT,      /* linux:74 (KEY_KPMINUS) -> linux:74 (KEY_KPMINUS) -> qcode:Q_KEY_CODE_KP_SUBTRACT (kp_subtract) */
	Q_KEY_CODE_KP_4,             /* linux:75 (KEY_KP4) -> linux:75 (KEY_KP4) -> qcode:Q_KEY_CODE_KP_4 (kp_4) */
	Q_KEY_CODE_KP_5,             /* linux:76 (KEY_KP5) -> linux:76 (KEY_KP5) -> qcode:Q_KEY_CODE_KP_5 (kp_5) */
	Q_KEY_CODE_KP_6,             /* linux:77 (KEY_KP6) -> linux:77 (KEY_KP6) -> qcode:Q_KEY_CODE_KP_6 (kp_6) */
	Q_KEY_CODE_KP_ADD,           /* linux:78 (KEY_KPPLUS) -> linux:78 (KEY_KPPLUS) -> qcode:Q_KEY_CODE_KP_ADD (kp_add) */
	Q_KEY_CODE_KP_1,             /* linux:79 (KEY_KP1) -> linux:79 (KEY_KP1) -> qcode:Q_KEY_CODE_KP_1 (kp_1) */
	Q_KEY_CODE_KP_2,             /* linux:80 (KEY_KP2) -> linux:80 (KEY_KP2) -> qcode:Q_KEY_CODE_KP_2 (kp_2) */
	Q_KEY_CODE_KP_3,             /* linux:81 (KEY_KP3) -> linux:81 (KEY_KP3) -> qcode:Q_KEY_CODE_KP_3 (kp_3) */
	Q_KEY_CODE_KP_0,             /* linux:82 (KEY_KP0) -> linux:82 (KEY_KP0) -> qcode:Q_KEY_CODE_KP_0 (kp_0) */
	Q_KEY_CODE_KP_DECIMAL,       /* linux:83 (KEY_KPDOT) -> linux:83 (KEY_KPDOT) -> qcode:Q_KEY_CODE_KP_DECIMAL (kp_decimal) */
	Q_KEY_CODE_UNMAPPED,         /* linux:84 (unnamed) -> linux:84 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:85 (KEY_ZENKAKUHANKAKU) -> linux:85 (KEY_ZENKAKUHANKAKU) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_LESS,             /* linux:86 (KEY_102ND) -> linux:86 (KEY_102ND) -> qcode:Q_KEY_CODE_LESS (less) */
	Q_KEY_CODE_F11,              /* linux:87 (KEY_F11) -> linux:87 (KEY_F11) -> qcode:Q_KEY_CODE_F11 (f11) */
	Q_KEY_CODE_F12,              /* linux:88 (KEY_F12) -> linux:88 (KEY_F12) -> qcode:Q_KEY_CODE_F12 (f12) */
	Q_KEY_CODE_RO,               /* linux:89 (KEY_RO) -> linux:89 (KEY_RO) -> qcode:Q_KEY_CODE_RO (ro) */
	Q_KEY_CODE_UNMAPPED,         /* linux:90 (KEY_KATAKANA) -> linux:90 (KEY_KATAKANA) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_HIRAGANA,         /* linux:91 (KEY_HIRAGANA) -> linux:91 (KEY_HIRAGANA) -> qcode:Q_KEY_CODE_HIRAGANA (hiragana) */
	Q_KEY_CODE_HENKAN,           /* linux:92 (KEY_HENKAN) -> linux:92 (KEY_HENKAN) -> qcode:Q_KEY_CODE_HENKAN (henkan) */
	Q_KEY_CODE_KATAKANAHIRAGANA, /* linux:93 (KEY_KATAKANAHIRAGANA) -> linux:93 (KEY_KATAKANAHIRAGANA) -> qcode:Q_KEY_CODE_KATAKANAHIRAGANA (katakanahiragana) */
	Q_KEY_CODE_MUHENKAN,         /* linux:94 (KEY_MUHENKAN) -> linux:94 (KEY_MUHENKAN) -> qcode:Q_KEY_CODE_MUHENKAN (muhenkan) */
	Q_KEY_CODE_UNMAPPED,         /* linux:95 (KEY_KPJPCOMMA) -> linux:95 (KEY_KPJPCOMMA) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_KP_ENTER,         /* linux:96 (KEY_KPENTER) -> linux:96 (KEY_KPENTER) -> qcode:Q_KEY_CODE_KP_ENTER (kp_enter) */
	Q_KEY_CODE_CTRL_R,           /* linux:97 (KEY_RIGHTCTRL) -> linux:97 (KEY_RIGHTCTRL) -> qcode:Q_KEY_CODE_CTRL_R (ctrl_r) */
	Q_KEY_CODE_KP_DIVIDE,        /* linux:98 (KEY_KPSLASH) -> linux:98 (KEY_KPSLASH) -> qcode:Q_KEY_CODE_KP_DIVIDE (kp_divide) */
	Q_KEY_CODE_SYSRQ,            /* linux:99 (KEY_SYSRQ) -> linux:99 (KEY_SYSRQ) -> qcode:Q_KEY_CODE_SYSRQ (sysrq) */
	Q_KEY_CODE_ALT_R,            /* linux:100 (KEY_RIGHTALT) -> linux:100 (KEY_RIGHTALT) -> qcode:Q_KEY_CODE_ALT_R (alt_r) */
	Q_KEY_CODE_LF,               /* linux:101 (KEY_LINEFEED) -> linux:101 (KEY_LINEFEED) -> qcode:Q_KEY_CODE_LF (lf) */
	Q_KEY_CODE_HOME,             /* linux:102 (KEY_HOME) -> linux:102 (KEY_HOME) -> qcode:Q_KEY_CODE_HOME (home) */
	Q_KEY_CODE_UP,               /* linux:103 (KEY_UP) -> linux:103 (KEY_UP) -> qcode:Q_KEY_CODE_UP (up) */
	Q_KEY_CODE_PGUP,             /* linux:104 (KEY_PAGEUP) -> linux:104 (KEY_PAGEUP) -> qcode:Q_KEY_CODE_PGUP (pgup) */
	Q_KEY_CODE_LEFT,             /* linux:105 (KEY_LEFT) -> linux:105 (KEY_LEFT) -> qcode:Q_KEY_CODE_LEFT (left) */
	Q_KEY_CODE_RIGHT,            /* linux:106 (KEY_RIGHT) -> linux:106 (KEY_RIGHT) -> qcode:Q_KEY_CODE_RIGHT (right) */
	Q_KEY_CODE_END,              /* linux:107 (KEY_END) -> linux:107 (KEY_END) -> qcode:Q_KEY_CODE_END (end) */
	Q_KEY_CODE_DOWN,             /* linux:108 (KEY_DOWN) -> linux:108 (KEY_DOWN) -> qcode:Q_KEY_CODE_DOWN (down) */
	Q_KEY_CODE_PGDN,             /* linux:109 (KEY_PAGEDOWN) -> linux:109 (KEY_PAGEDOWN) -> qcode:Q_KEY_CODE_PGDN (pgdn) */
	Q_KEY_CODE_INSERT,           /* linux:110 (KEY_INSERT) -> linux:110 (KEY_INSERT) -> qcode:Q_KEY_CODE_INSERT (insert) */
	Q_KEY_CODE_DELETE,           /* linux:111 (KEY_DELETE) -> linux:111 (KEY_DELETE) -> qcode:Q_KEY_CODE_DELETE (delete) */
	Q_KEY_CODE_UNMAPPED,         /* linux:112 (KEY_MACRO) -> linux:112 (KEY_MACRO) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_AUDIOMUTE,        /* linux:113 (KEY_MUTE) -> linux:113 (KEY_MUTE) -> qcode:Q_KEY_CODE_AUDIOMUTE (audiomute) */
	Q_KEY_CODE_VOLUMEDOWN,       /* linux:114 (KEY_VOLUMEDOWN) -> linux:114 (KEY_VOLUMEDOWN) -> qcode:Q_KEY_CODE_VOLUMEDOWN (volumedown) */
	Q_KEY_CODE_VOLUMEUP,         /* linux:115 (KEY_VOLUMEUP) -> linux:115 (KEY_VOLUMEUP) -> qcode:Q_KEY_CODE_VOLUMEUP (volumeup) */
	Q_KEY_CODE_POWER,            /* linux:116 (KEY_POWER) -> linux:116 (KEY_POWER) -> qcode:Q_KEY_CODE_POWER (power) */
	Q_KEY_CODE_KP_EQUALS,        /* linux:117 (KEY_KPEQUAL) -> linux:117 (KEY_KPEQUAL) -> qcode:Q_KEY_CODE_KP_EQUALS (kp_equals) */
	Q_KEY_CODE_UNMAPPED,         /* linux:118 (KEY_KPPLUSMINUS) -> linux:118 (KEY_KPPLUSMINUS) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_PAUSE,            /* linux:119 (KEY_PAUSE) -> linux:119 (KEY_PAUSE) -> qcode:Q_KEY_CODE_PAUSE (pause) */
	Q_KEY_CODE_UNMAPPED,         /* linux:120 (KEY_SCALE) -> linux:120 (KEY_SCALE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_KP_COMMA,         /* linux:121 (KEY_KPCOMMA) -> linux:121 (KEY_KPCOMMA) -> qcode:Q_KEY_CODE_KP_COMMA (kp_comma) */
	Q_KEY_CODE_UNMAPPED,         /* linux:122 (KEY_HANGEUL) -> linux:122 (KEY_HANGEUL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:123 (KEY_HANJA) -> linux:123 (KEY_HANJA) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_YEN,              /* linux:124 (KEY_YEN) -> linux:124 (KEY_YEN) -> qcode:Q_KEY_CODE_YEN (yen) */
	Q_KEY_CODE_META_L,           /* linux:125 (KEY_LEFTMETA) -> linux:125 (KEY_LEFTMETA) -> qcode:Q_KEY_CODE_META_L (meta_l) */
	Q_KEY_CODE_META_R,           /* linux:126 (KEY_RIGHTMETA) -> linux:126 (KEY_RIGHTMETA) -> qcode:Q_KEY_CODE_META_R (meta_r) */
	Q_KEY_CODE_COMPOSE,          /* linux:127 (KEY_COMPOSE) -> linux:127 (KEY_COMPOSE) -> qcode:Q_KEY_CODE_COMPOSE (compose) */
	Q_KEY_CODE_STOP,             /* linux:128 (KEY_STOP) -> linux:128 (KEY_STOP) -> qcode:Q_KEY_CODE_STOP (stop) */
	Q_KEY_CODE_AGAIN,            /* linux:129 (KEY_AGAIN) -> linux:129 (KEY_AGAIN) -> qcode:Q_KEY_CODE_AGAIN (again) */
	Q_KEY_CODE_PROPS,            /* linux:130 (KEY_PROPS) -> linux:130 (KEY_PROPS) -> qcode:Q_KEY_CODE_PROPS (props) */
	Q_KEY_CODE_UNDO,             /* linux:131 (KEY_UNDO) -> linux:131 (KEY_UNDO) -> qcode:Q_KEY_CODE_UNDO (undo) */
	Q_KEY_CODE_FRONT,            /* linux:132 (KEY_FRONT) -> linux:132 (KEY_FRONT) -> qcode:Q_KEY_CODE_FRONT (front) */
	Q_KEY_CODE_COPY,             /* linux:133 (KEY_COPY) -> linux:133 (KEY_COPY) -> qcode:Q_KEY_CODE_COPY (copy) */
	Q_KEY_CODE_OPEN,             /* linux:134 (KEY_OPEN) -> linux:134 (KEY_OPEN) -> qcode:Q_KEY_CODE_OPEN (open) */
	Q_KEY_CODE_PASTE,            /* linux:135 (KEY_PASTE) -> linux:135 (KEY_PASTE) -> qcode:Q_KEY_CODE_PASTE (paste) */
	Q_KEY_CODE_FIND,             /* linux:136 (KEY_FIND) -> linux:136 (KEY_FIND) -> qcode:Q_KEY_CODE_FIND (find) */
	Q_KEY_CODE_CUT,              /* linux:137 (KEY_CUT) -> linux:137 (KEY_CUT) -> qcode:Q_KEY_CODE_CUT (cut) */
	Q_KEY_CODE_HELP,             /* linux:138 (KEY_HELP) -> linux:138 (KEY_HELP) -> qcode:Q_KEY_CODE_HELP (help) */
	Q_KEY_CODE_MENU,             /* linux:139 (KEY_MENU) -> linux:139 (KEY_MENU) -> qcode:Q_KEY_CODE_MENU (menu) */
	Q_KEY_CODE_CALCULATOR,       /* linux:140 (KEY_CALC) -> linux:140 (KEY_CALC) -> qcode:Q_KEY_CODE_CALCULATOR (calculator) */
	Q_KEY_CODE_UNMAPPED,         /* linux:141 (KEY_SETUP) -> linux:141 (KEY_SETUP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_SLEEP,            /* linux:142 (KEY_SLEEP) -> linux:142 (KEY_SLEEP) -> qcode:Q_KEY_CODE_SLEEP (sleep) */
	Q_KEY_CODE_WAKE,             /* linux:143 (KEY_WAKEUP) -> linux:143 (KEY_WAKEUP) -> qcode:Q_KEY_CODE_WAKE (wake) */
	Q_KEY_CODE_UNMAPPED,         /* linux:144 (KEY_FILE) -> linux:144 (KEY_FILE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:145 (KEY_SENDFILE) -> linux:145 (KEY_SENDFILE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:146 (KEY_DELETEFILE) -> linux:146 (KEY_DELETEFILE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:147 (KEY_XFER) -> linux:147 (KEY_XFER) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:148 (KEY_PROG1) -> linux:148 (KEY_PROG1) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:149 (KEY_PROG2) -> linux:149 (KEY_PROG2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:150 (KEY_WWW) -> linux:150 (KEY_WWW) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:151 (KEY_MSDOS) -> linux:151 (KEY_MSDOS) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:152 (KEY_SCREENLOCK) -> linux:152 (KEY_SCREENLOCK) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:153 (KEY_DIRECTION) -> linux:153 (KEY_DIRECTION) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:154 (KEY_CYCLEWINDOWS) -> linux:154 (KEY_CYCLEWINDOWS) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_MAIL,             /* linux:155 (KEY_MAIL) -> linux:155 (KEY_MAIL) -> qcode:Q_KEY_CODE_MAIL (mail) */
	Q_KEY_CODE_AC_BOOKMARKS,     /* linux:156 (KEY_BOOKMARKS) -> linux:156 (KEY_BOOKMARKS) -> qcode:Q_KEY_CODE_AC_BOOKMARKS (ac_bookmarks) */
	Q_KEY_CODE_COMPUTER,         /* linux:157 (KEY_COMPUTER) -> linux:157 (KEY_COMPUTER) -> qcode:Q_KEY_CODE_COMPUTER (computer) */
	Q_KEY_CODE_AC_BACK,          /* linux:158 (KEY_BACK) -> linux:158 (KEY_BACK) -> qcode:Q_KEY_CODE_AC_BACK (ac_back) */
	Q_KEY_CODE_AC_FORWARD,       /* linux:159 (KEY_FORWARD) -> linux:159 (KEY_FORWARD) -> qcode:Q_KEY_CODE_AC_FORWARD (ac_forward) */
	Q_KEY_CODE_UNMAPPED,         /* linux:160 (KEY_CLOSECD) -> linux:160 (KEY_CLOSECD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:161 (KEY_EJECTCD) -> linux:161 (KEY_EJECTCD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:162 (KEY_EJECTCLOSECD) -> linux:162 (KEY_EJECTCLOSECD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_AUDIONEXT,        /* linux:163 (KEY_NEXTSONG) -> linux:163 (KEY_NEXTSONG) -> qcode:Q_KEY_CODE_AUDIONEXT (audionext) */
	Q_KEY_CODE_AUDIOPLAY,        /* linux:164 (KEY_PLAYPAUSE) -> linux:164 (KEY_PLAYPAUSE) -> qcode:Q_KEY_CODE_AUDIOPLAY (audioplay) */
	Q_KEY_CODE_AUDIOPREV,        /* linux:165 (KEY_PREVIOUSSONG) -> linux:165 (KEY_PREVIOUSSONG) -> qcode:Q_KEY_CODE_AUDIOPREV (audioprev) */
	Q_KEY_CODE_AUDIOSTOP,        /* linux:166 (KEY_STOPCD) -> linux:166 (KEY_STOPCD) -> qcode:Q_KEY_CODE_AUDIOSTOP (audiostop) */
	Q_KEY_CODE_UNMAPPED,         /* linux:167 (KEY_RECORD) -> linux:167 (KEY_RECORD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:168 (KEY_REWIND) -> linux:168 (KEY_REWIND) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:169 (KEY_PHONE) -> linux:169 (KEY_PHONE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:170 (KEY_ISO) -> linux:170 (KEY_ISO) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:171 (KEY_CONFIG) -> linux:171 (KEY_CONFIG) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_AC_HOME,          /* linux:172 (KEY_HOMEPAGE) -> linux:172 (KEY_HOMEPAGE) -> qcode:Q_KEY_CODE_AC_HOME (ac_home) */
	Q_KEY_CODE_AC_REFRESH,       /* linux:173 (KEY_REFRESH) -> linux:173 (KEY_REFRESH) -> qcode:Q_KEY_CODE_AC_REFRESH (ac_refresh) */
	Q_KEY_CODE_UNMAPPED,         /* linux:174 (KEY_EXIT) -> linux:174 (KEY_EXIT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:175 (KEY_MOVE) -> linux:175 (KEY_MOVE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:176 (KEY_EDIT) -> linux:176 (KEY_EDIT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:177 (KEY_SCROLLUP) -> linux:177 (KEY_SCROLLUP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:178 (KEY_SCROLLDOWN) -> linux:178 (KEY_SCROLLDOWN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:179 (KEY_KPLEFTPAREN) -> linux:179 (KEY_KPLEFTPAREN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:180 (KEY_KPRIGHTPAREN) -> linux:180 (KEY_KPRIGHTPAREN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:181 (KEY_NEW) -> linux:181 (KEY_NEW) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:182 (KEY_REDO) -> linux:182 (KEY_REDO) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:183 (KEY_F13) -> linux:183 (KEY_F13) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:184 (KEY_F14) -> linux:184 (KEY_F14) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:185 (KEY_F15) -> linux:185 (KEY_F15) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:186 (KEY_F16) -> linux:186 (KEY_F16) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:187 (KEY_F17) -> linux:187 (KEY_F17) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:188 (KEY_F18) -> linux:188 (KEY_F18) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:189 (KEY_F19) -> linux:189 (KEY_F19) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:190 (KEY_F20) -> linux:190 (KEY_F20) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:191 (KEY_F21) -> linux:191 (KEY_F21) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:192 (KEY_F22) -> linux:192 (KEY_F22) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:193 (KEY_F23) -> linux:193 (KEY_F23) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:194 (KEY_F24) -> linux:194 (KEY_F24) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:195 (unnamed) -> linux:195 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:196 (unnamed) -> linux:196 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:197 (unnamed) -> linux:197 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:198 (unnamed) -> linux:198 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:199 (unnamed) -> linux:199 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:200 (KEY_PLAYCD) -> linux:200 (KEY_PLAYCD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:201 (KEY_PAUSECD) -> linux:201 (KEY_PAUSECD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:202 (KEY_PROG3) -> linux:202 (KEY_PROG3) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:203 (KEY_PROG4) -> linux:203 (KEY_PROG4) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:204 (KEY_DASHBOARD) -> linux:204 (KEY_DASHBOARD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:205 (KEY_SUSPEND) -> linux:205 (KEY_SUSPEND) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:206 (KEY_CLOSE) -> linux:206 (KEY_CLOSE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:207 (KEY_PLAY) -> linux:207 (KEY_PLAY) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:208 (KEY_FASTFORWARD) -> linux:208 (KEY_FASTFORWARD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:209 (KEY_BASSBOOST) -> linux:209 (KEY_BASSBOOST) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:210 (KEY_PRINT) -> linux:210 (KEY_PRINT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:211 (KEY_HP) -> linux:211 (KEY_HP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:212 (KEY_CAMERA) -> linux:212 (KEY_CAMERA) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:213 (KEY_SOUND) -> linux:213 (KEY_SOUND) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:214 (KEY_QUESTION) -> linux:214 (KEY_QUESTION) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:215 (KEY_EMAIL) -> linux:215 (KEY_EMAIL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:216 (KEY_CHAT) -> linux:216 (KEY_CHAT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:217 (KEY_SEARCH) -> linux:217 (KEY_SEARCH) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:218 (KEY_CONNECT) -> linux:218 (KEY_CONNECT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:219 (KEY_FINANCE) -> linux:219 (KEY_FINANCE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:220 (KEY_SPORT) -> linux:220 (KEY_SPORT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:221 (KEY_SHOP) -> linux:221 (KEY_SHOP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:222 (KEY_ALTERASE) -> linux:222 (KEY_ALTERASE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:223 (KEY_CANCEL) -> linux:223 (KEY_CANCEL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:224 (KEY_BRIGHTNESSDOWN) -> linux:224 (KEY_BRIGHTNESSDOWN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:225 (KEY_BRIGHTNESSUP) -> linux:225 (KEY_BRIGHTNESSUP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_MEDIASELECT,      /* linux:226 (KEY_MEDIA) -> linux:226 (KEY_MEDIA) -> qcode:Q_KEY_CODE_MEDIASELECT (mediaselect) */
	Q_KEY_CODE_UNMAPPED,         /* linux:227 (KEY_SWITCHVIDEOMODE) -> linux:227 (KEY_SWITCHVIDEOMODE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:228 (KEY_KBDILLUMTOGGLE) -> linux:228 (KEY_KBDILLUMTOGGLE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:229 (KEY_KBDILLUMDOWN) -> linux:229 (KEY_KBDILLUMDOWN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:230 (KEY_KBDILLUMUP) -> linux:230 (KEY_KBDILLUMUP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:231 (KEY_SEND) -> linux:231 (KEY_SEND) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:232 (KEY_REPLY) -> linux:232 (KEY_REPLY) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:233 (KEY_FORWARDMAIL) -> linux:233 (KEY_FORWARDMAIL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:234 (KEY_SAVE) -> linux:234 (KEY_SAVE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:235 (KEY_DOCUMENTS) -> linux:235 (KEY_DOCUMENTS) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:236 (KEY_BATTERY) -> linux:236 (KEY_BATTERY) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:237 (KEY_BLUETOOTH) -> linux:237 (KEY_BLUETOOTH) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:238 (KEY_WLAN) -> linux:238 (KEY_WLAN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:239 (KEY_UWB) -> linux:239 (KEY_UWB) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:240 (KEY_UNKNOWN) -> linux:240 (KEY_UNKNOWN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:241 (KEY_VIDEO_NEXT) -> linux:241 (KEY_VIDEO_NEXT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:242 (KEY_VIDEO_PREV) -> linux:242 (KEY_VIDEO_PREV) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:243 (KEY_BRIGHTNESS_CYCLE) -> linux:243 (KEY_BRIGHTNESS_CYCLE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:244 (KEY_BRIGHTNESS_ZERO) -> linux:244 (KEY_BRIGHTNESS_ZERO) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:245 (KEY_DISPLAY_OFF) -> linux:245 (KEY_DISPLAY_OFF) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:246 (KEY_WIMAX) -> linux:246 (KEY_WIMAX) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:247 (unnamed) -> linux:247 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:248 (unnamed) -> linux:248 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:249 (unnamed) -> linux:249 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:250 (unnamed) -> linux:250 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:251 (unnamed) -> linux:251 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:252 (unnamed) -> linux:252 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:253 (unnamed) -> linux:253 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:254 (unnamed) -> linux:254 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:255 (unnamed) -> linux:255 (unnamed) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:256 (BTN_0) -> linux:256 (BTN_0) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:257 (BTN_1) -> linux:257 (BTN_1) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:258 (BTN_2) -> linux:258 (BTN_2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:259 (BTN_3) -> linux:259 (BTN_3) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:260 (BTN_4) -> linux:260 (BTN_4) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:261 (BTN_5) -> linux:261 (BTN_5) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:262 (BTN_6) -> linux:262 (BTN_6) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:263 (BTN_7) -> linux:263 (BTN_7) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:264 (BTN_8) -> linux:264 (BTN_8) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:265 (BTN_9) -> linux:265 (BTN_9) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:266 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:267 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:268 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:269 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:270 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:271 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:272 (BTN_LEFT) -> linux:272 (BTN_LEFT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:273 (BTN_RIGHT) -> linux:273 (BTN_RIGHT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:274 (BTN_MIDDLE) -> linux:274 (BTN_MIDDLE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:275 (BTN_SIDE) -> linux:275 (BTN_SIDE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:276 (BTN_EXTRA) -> linux:276 (BTN_EXTRA) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:277 (BTN_FORWARD) -> linux:277 (BTN_FORWARD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:278 (BTN_BACK) -> linux:278 (BTN_BACK) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:279 (BTN_TASK) -> linux:279 (BTN_TASK) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:280 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:281 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:282 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:283 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:284 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:285 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:286 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:287 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:288 (BTN_TRIGGER) -> linux:288 (BTN_TRIGGER) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:289 (BTN_THUMB) -> linux:289 (BTN_THUMB) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:290 (BTN_THUMB2) -> linux:290 (BTN_THUMB2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:291 (BTN_TOP) -> linux:291 (BTN_TOP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:292 (BTN_TOP2) -> linux:292 (BTN_TOP2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:293 (BTN_PINKIE) -> linux:293 (BTN_PINKIE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:294 (BTN_BASE) -> linux:294 (BTN_BASE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:295 (BTN_BASE2) -> linux:295 (BTN_BASE2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:296 (BTN_BASE3) -> linux:296 (BTN_BASE3) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:297 (BTN_BASE4) -> linux:297 (BTN_BASE4) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:298 (BTN_BASE5) -> linux:298 (BTN_BASE5) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:299 (BTN_BASE6) -> linux:299 (BTN_BASE6) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:300 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:301 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:302 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:303 (BTN_DEAD) -> linux:303 (BTN_DEAD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:304 (BTN_A) -> linux:304 (BTN_A) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:305 (BTN_B) -> linux:305 (BTN_B) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:306 (BTN_C) -> linux:306 (BTN_C) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:307 (BTN_X) -> linux:307 (BTN_X) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:308 (BTN_Y) -> linux:308 (BTN_Y) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:309 (BTN_Z) -> linux:309 (BTN_Z) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:310 (BTN_TL) -> linux:310 (BTN_TL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:311 (BTN_TR) -> linux:311 (BTN_TR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:312 (BTN_TL2) -> linux:312 (BTN_TL2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:313 (BTN_TR2) -> linux:313 (BTN_TR2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:314 (BTN_SELECT) -> linux:314 (BTN_SELECT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:315 (BTN_START) -> linux:315 (BTN_START) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:316 (BTN_MODE) -> linux:316 (BTN_MODE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:317 (BTN_THUMBL) -> linux:317 (BTN_THUMBL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:318 (BTN_THUMBR) -> linux:318 (BTN_THUMBR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:319 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:320 (BTN_TOOL_PEN) -> linux:320 (BTN_TOOL_PEN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:321 (BTN_TOOL_RUBBER) -> linux:321 (BTN_TOOL_RUBBER) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:322 (BTN_TOOL_BRUSH) -> linux:322 (BTN_TOOL_BRUSH) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:323 (BTN_TOOL_PENCIL) -> linux:323 (BTN_TOOL_PENCIL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:324 (BTN_TOOL_AIRBRUSH) -> linux:324 (BTN_TOOL_AIRBRUSH) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:325 (BTN_TOOL_FINGER) -> linux:325 (BTN_TOOL_FINGER) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:326 (BTN_TOOL_MOUSE) -> linux:326 (BTN_TOOL_MOUSE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:327 (BTN_TOOL_LENS) -> linux:327 (BTN_TOOL_LENS) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:328 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:329 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:330 (BTN_TOUCH) -> linux:330 (BTN_TOUCH) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:331 (BTN_STYLUS) -> linux:331 (BTN_STYLUS) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:332 (BTN_STYLUS2) -> linux:332 (BTN_STYLUS2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:333 (BTN_TOOL_DOUBLETAP) -> linux:333 (BTN_TOOL_DOUBLETAP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:334 (BTN_TOOL_TRIPLETAP) -> linux:334 (BTN_TOOL_TRIPLETAP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:335 (BTN_TOOL_QUADTAP) -> linux:335 (BTN_TOOL_QUADTAP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:336 (BTN_GEAR_DOWN) -> linux:336 (BTN_GEAR_DOWN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:337 (BTN_GEAR_UP) -> linux:337 (BTN_GEAR_UP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:338 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:339 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:340 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:341 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:342 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:343 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:344 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:345 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:346 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:347 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:348 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:349 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:350 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:351 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:352 (KEY_OK) -> linux:352 (KEY_OK) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:353 (KEY_SELECT) -> linux:353 (KEY_SELECT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:354 (KEY_GOTO) -> linux:354 (KEY_GOTO) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:355 (KEY_CLEAR) -> linux:355 (KEY_CLEAR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:356 (KEY_POWER2) -> linux:356 (KEY_POWER2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:357 (KEY_OPTION) -> linux:357 (KEY_OPTION) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:358 (KEY_INFO) -> linux:358 (KEY_INFO) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:359 (KEY_TIME) -> linux:359 (KEY_TIME) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:360 (KEY_VENDOR) -> linux:360 (KEY_VENDOR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:361 (KEY_ARCHIVE) -> linux:361 (KEY_ARCHIVE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:362 (KEY_PROGRAM) -> linux:362 (KEY_PROGRAM) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:363 (KEY_CHANNEL) -> linux:363 (KEY_CHANNEL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:364 (KEY_FAVORITES) -> linux:364 (KEY_FAVORITES) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:365 (KEY_EPG) -> linux:365 (KEY_EPG) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:366 (KEY_PVR) -> linux:366 (KEY_PVR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:367 (KEY_MHP) -> linux:367 (KEY_MHP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:368 (KEY_LANGUAGE) -> linux:368 (KEY_LANGUAGE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:369 (KEY_TITLE) -> linux:369 (KEY_TITLE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:370 (KEY_SUBTITLE) -> linux:370 (KEY_SUBTITLE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:371 (KEY_ANGLE) -> linux:371 (KEY_ANGLE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:372 (KEY_ZOOM) -> linux:372 (KEY_ZOOM) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:373 (KEY_MODE) -> linux:373 (KEY_MODE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:374 (KEY_KEYBOARD) -> linux:374 (KEY_KEYBOARD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:375 (KEY_SCREEN) -> linux:375 (KEY_SCREEN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:376 (KEY_PC) -> linux:376 (KEY_PC) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:377 (KEY_TV) -> linux:377 (KEY_TV) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:378 (KEY_TV2) -> linux:378 (KEY_TV2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:379 (KEY_VCR) -> linux:379 (KEY_VCR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:380 (KEY_VCR2) -> linux:380 (KEY_VCR2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:381 (KEY_SAT) -> linux:381 (KEY_SAT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:382 (KEY_SAT2) -> linux:382 (KEY_SAT2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:383 (KEY_CD) -> linux:383 (KEY_CD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:384 (KEY_TAPE) -> linux:384 (KEY_TAPE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:385 (KEY_RADIO) -> linux:385 (KEY_RADIO) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:386 (KEY_TUNER) -> linux:386 (KEY_TUNER) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:387 (KEY_PLAYER) -> linux:387 (KEY_PLAYER) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:388 (KEY_TEXT) -> linux:388 (KEY_TEXT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:389 (KEY_DVD) -> linux:389 (KEY_DVD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:390 (KEY_AUX) -> linux:390 (KEY_AUX) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:391 (KEY_MP3) -> linux:391 (KEY_MP3) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:392 (KEY_AUDIO) -> linux:392 (KEY_AUDIO) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:393 (KEY_VIDEO) -> linux:393 (KEY_VIDEO) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:394 (KEY_DIRECTORY) -> linux:394 (KEY_DIRECTORY) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:395 (KEY_LIST) -> linux:395 (KEY_LIST) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:396 (KEY_MEMO) -> linux:396 (KEY_MEMO) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:397 (KEY_CALENDAR) -> linux:397 (KEY_CALENDAR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:398 (KEY_RED) -> linux:398 (KEY_RED) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:399 (KEY_GREEN) -> linux:399 (KEY_GREEN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:400 (KEY_YELLOW) -> linux:400 (KEY_YELLOW) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:401 (KEY_BLUE) -> linux:401 (KEY_BLUE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:402 (KEY_CHANNELUP) -> linux:402 (KEY_CHANNELUP) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:403 (KEY_CHANNELDOWN) -> linux:403 (KEY_CHANNELDOWN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:404 (KEY_FIRST) -> linux:404 (KEY_FIRST) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:405 (KEY_LAST) -> linux:405 (KEY_LAST) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:406 (KEY_AB) -> linux:406 (KEY_AB) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:407 (KEY_NEXT) -> linux:407 (KEY_NEXT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:408 (KEY_RESTART) -> linux:408 (KEY_RESTART) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:409 (KEY_SLOW) -> linux:409 (KEY_SLOW) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:410 (KEY_SHUFFLE) -> linux:410 (KEY_SHUFFLE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:411 (KEY_BREAK) -> linux:411 (KEY_BREAK) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:412 (KEY_PREVIOUS) -> linux:412 (KEY_PREVIOUS) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:413 (KEY_DIGITS) -> linux:413 (KEY_DIGITS) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:414 (KEY_TEEN) -> linux:414 (KEY_TEEN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:415 (KEY_TWEN) -> linux:415 (KEY_TWEN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:416 (KEY_VIDEOPHONE) -> linux:416 (KEY_VIDEOPHONE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:417 (KEY_GAMES) -> linux:417 (KEY_GAMES) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:418 (KEY_ZOOMIN) -> linux:418 (KEY_ZOOMIN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:419 (KEY_ZOOMOUT) -> linux:419 (KEY_ZOOMOUT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:420 (KEY_ZOOMRESET) -> linux:420 (KEY_ZOOMRESET) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:421 (KEY_WORDPROCESSOR) -> linux:421 (KEY_WORDPROCESSOR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:422 (KEY_EDITOR) -> linux:422 (KEY_EDITOR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:423 (KEY_SPREADSHEET) -> linux:423 (KEY_SPREADSHEET) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:424 (KEY_GRAPHICSEDITOR) -> linux:424 (KEY_GRAPHICSEDITOR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:425 (KEY_PRESENTATION) -> linux:425 (KEY_PRESENTATION) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:426 (KEY_DATABASE) -> linux:426 (KEY_DATABASE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:427 (KEY_NEWS) -> linux:427 (KEY_NEWS) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:428 (KEY_VOICEMAIL) -> linux:428 (KEY_VOICEMAIL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:429 (KEY_ADDRESSBOOK) -> linux:429 (KEY_ADDRESSBOOK) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:430 (KEY_MESSENGER) -> linux:430 (KEY_MESSENGER) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:431 (KEY_DISPLAYTOGGLE) -> linux:431 (KEY_DISPLAYTOGGLE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:432 (KEY_SPELLCHECK) -> linux:432 (KEY_SPELLCHECK) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:433 (KEY_LOGOFF) -> linux:433 (KEY_LOGOFF) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:434 (KEY_DOLLAR) -> linux:434 (KEY_DOLLAR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:435 (KEY_EURO) -> linux:435 (KEY_EURO) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:436 (KEY_FRAMEBACK) -> linux:436 (KEY_FRAMEBACK) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:437 (KEY_FRAMEFORWARD) -> linux:437 (KEY_FRAMEFORWARD) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:438 (KEY_CONTEXT_MENU) -> linux:438 (KEY_CONTEXT_MENU) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:439 (KEY_MEDIA_REPEAT) -> linux:439 (KEY_MEDIA_REPEAT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:440 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:441 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:442 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:443 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:444 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:445 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:446 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:447 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:448 (KEY_DEL_EOL) -> linux:448 (KEY_DEL_EOL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:449 (KEY_DEL_EOS) -> linux:449 (KEY_DEL_EOS) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:450 (KEY_INS_LINE) -> linux:450 (KEY_INS_LINE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:451 (KEY_DEL_LINE) -> linux:451 (KEY_DEL_LINE) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:452 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:453 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:454 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:455 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:456 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:457 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:458 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:459 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:460 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:461 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:462 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:463 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:464 (KEY_FN) -> linux:464 (KEY_FN) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:465 (KEY_FN_ESC) -> linux:465 (KEY_FN_ESC) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:466 (KEY_FN_F1) -> linux:466 (KEY_FN_F1) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:467 (KEY_FN_F2) -> linux:467 (KEY_FN_F2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:468 (KEY_FN_F3) -> linux:468 (KEY_FN_F3) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:469 (KEY_FN_F4) -> linux:469 (KEY_FN_F4) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:470 (KEY_FN_F5) -> linux:470 (KEY_FN_F5) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:471 (KEY_FN_F6) -> linux:471 (KEY_FN_F6) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:472 (KEY_FN_F7) -> linux:472 (KEY_FN_F7) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:473 (KEY_FN_F8) -> linux:473 (KEY_FN_F8) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:474 (KEY_FN_F9) -> linux:474 (KEY_FN_F9) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:475 (KEY_FN_F10) -> linux:475 (KEY_FN_F10) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:476 (KEY_FN_F11) -> linux:476 (KEY_FN_F11) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:477 (KEY_FN_F12) -> linux:477 (KEY_FN_F12) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:478 (KEY_FN_1) -> linux:478 (KEY_FN_1) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:479 (KEY_FN_2) -> linux:479 (KEY_FN_2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:480 (KEY_FN_D) -> linux:480 (KEY_FN_D) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:481 (KEY_FN_E) -> linux:481 (KEY_FN_E) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:482 (KEY_FN_F) -> linux:482 (KEY_FN_F) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:483 (KEY_FN_S) -> linux:483 (KEY_FN_S) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:484 (KEY_FN_B) -> linux:484 (KEY_FN_B) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:485 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:486 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:487 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:488 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:489 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:490 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:491 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:492 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:493 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:494 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:495 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:496 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:497 (KEY_BRL_DOT1) -> linux:497 (KEY_BRL_DOT1) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:498 (KEY_BRL_DOT2) -> linux:498 (KEY_BRL_DOT2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:499 (KEY_BRL_DOT3) -> linux:499 (KEY_BRL_DOT3) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:500 (KEY_BRL_DOT4) -> linux:500 (KEY_BRL_DOT4) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:501 (KEY_BRL_DOT5) -> linux:501 (KEY_BRL_DOT5) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:502 (KEY_BRL_DOT6) -> linux:502 (KEY_BRL_DOT6) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:503 (KEY_BRL_DOT7) -> linux:503 (KEY_BRL_DOT7) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:504 (KEY_BRL_DOT8) -> linux:504 (KEY_BRL_DOT8) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:505 (KEY_BRL_DOT9) -> linux:505 (KEY_BRL_DOT9) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:506 (KEY_BRL_DOT10) -> linux:506 (KEY_BRL_DOT10) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:507 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:508 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:509 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:510 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:511 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:512 (KEY_NUMERIC_0) -> linux:512 (KEY_NUMERIC_0) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:513 (KEY_NUMERIC_1) -> linux:513 (KEY_NUMERIC_1) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:514 (KEY_NUMERIC_2) -> linux:514 (KEY_NUMERIC_2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:515 (KEY_NUMERIC_3) -> linux:515 (KEY_NUMERIC_3) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:516 (KEY_NUMERIC_4) -> linux:516 (KEY_NUMERIC_4) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:517 (KEY_NUMERIC_5) -> linux:517 (KEY_NUMERIC_5) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:518 (KEY_NUMERIC_6) -> linux:518 (KEY_NUMERIC_6) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:519 (KEY_NUMERIC_7) -> linux:519 (KEY_NUMERIC_7) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:520 (KEY_NUMERIC_8) -> linux:520 (KEY_NUMERIC_8) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:521 (KEY_NUMERIC_9) -> linux:521 (KEY_NUMERIC_9) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:522 (KEY_NUMERIC_STAR) -> linux:522 (KEY_NUMERIC_STAR) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:523 (KEY_NUMERIC_POUND) -> linux:523 (KEY_NUMERIC_POUND) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,         /* linux:524 (KEY_RFKILL) -> linux:524 (KEY_RFKILL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
};
const size_t qemu_input_map_linux_to_qcode_len = sizeof(qemu_input_map_linux_to_qcode) / sizeof(qemu_input_map_linux_to_qcode[0]);
