/*  PCSX2 - PS2 Emulator for PCs
 *  Copyright (C) 2002-2020  PCSX2 Dev Team
 *
 *  PCSX2 is free software: you can redistribute it and/or modify it under the terms
 *  of the GNU Lesser General Public License as published by the Free Software Found-
 *  ation, either version 3 of the License, or (at your option) any later version.
 *
 *  PCSX2 is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 *  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 *  PURPOSE.  See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with PCSX2.
 *  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This file is auto-generated from keymaps.csv on 2018-12-22 15:48
 * To re-generate, run:
 *   keymap-gen --lang=stdc++ --varname=qemu_input_map_win32_to_qcode code-map keymaps.csv win32 qcode
*/
#include "PrecompiledHeader.h"
#include "input-keymap-win32-to-qcode.h"
const std::array<QKeyCode, 252> qemu_input_map_win32_to_qcode = {
	Q_KEY_CODE_UNMAPPED,      /* win32:0 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:1 (VK_LBUTTON) -> linux:256 (BTN_0) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:2 (VK_RBUTTON) -> linux:257 (BTN_1) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:3 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:4 (VK_MBUTTON) -> linux:258 (BTN_2) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:5 (VK_XBUTTON1) -> linux:259 (BTN_3) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:6 (VK_XBUTTON2) -> linux:260 (BTN_4) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:7 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_BACKSPACE,     /* win32:8 (VK_BACK) -> linux:14 (KEY_BACKSPACE) -> qcode:Q_KEY_CODE_BACKSPACE (backspace) */
	Q_KEY_CODE_TAB,           /* win32:9 (VK_TAB) -> linux:15 (KEY_TAB) -> qcode:Q_KEY_CODE_TAB (tab) */
	Q_KEY_CODE_UNMAPPED,      /* win32:10 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:11 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:12 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_RET,           /* win32:13 (VK_RETURN) -> linux:28 (KEY_ENTER) -> qcode:Q_KEY_CODE_RET (ret) */
	Q_KEY_CODE_UNMAPPED,      /* win32:14 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:15 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_SHIFT,         /* win32:16 (VK_LSHIFT) -> linux:42 (KEY_LEFTSHIFT) -> qcode:Q_KEY_CODE_SHIFT (shift) */
	Q_KEY_CODE_CTRL,          /* win32:17 (VK_CONTROL) -> linux:29 (KEY_LEFTCTRL) -> qcode:Q_KEY_CODE_CTRL (ctrl) */
	Q_KEY_CODE_ALT,           /* win32:18 (VK_MENU) -> linux:56 (KEY_LEFTALT) -> qcode:Q_KEY_CODE_ALT (alt) */
	Q_KEY_CODE_PAUSE,         /* win32:19 (VK_PAUSE) -> linux:119 (KEY_PAUSE) -> qcode:Q_KEY_CODE_PAUSE (pause) */
	Q_KEY_CODE_CAPS_LOCK,     /* win32:20 (VK_CAPITAL) -> linux:58 (KEY_CAPSLOCK) -> qcode:Q_KEY_CODE_CAPS_LOCK (caps_lock) */
	Q_KEY_CODE_UNMAPPED,      /* win32:21 (VK_HANGEUL) -> linux:122 (KEY_HANGEUL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:22 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:23 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:24 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:25 (VK_HANJA) -> linux:123 (KEY_HANJA) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:26 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_ESC,           /* win32:27 (VK_ESCAPE) -> linux:1 (KEY_ESC) -> qcode:Q_KEY_CODE_ESC (esc) */
	Q_KEY_CODE_UNMAPPED,      /* win32:28 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:29 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:30 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:31 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_SPC,           /* win32:32 (VK_SPACE) -> linux:57 (KEY_SPACE) -> qcode:Q_KEY_CODE_SPC (spc) */
	Q_KEY_CODE_PGUP,          /* win32:33 (VK_PRIOR) -> linux:104 (KEY_PAGEUP) -> qcode:Q_KEY_CODE_PGUP (pgup) */
	Q_KEY_CODE_PGDN,          /* win32:34 (VK_NEXT) -> linux:109 (KEY_PAGEDOWN) -> qcode:Q_KEY_CODE_PGDN (pgdn) */
	Q_KEY_CODE_END,           /* win32:35 (VK_END) -> linux:107 (KEY_END) -> qcode:Q_KEY_CODE_END (end) */
	Q_KEY_CODE_HOME,          /* win32:36 (VK_HOME) -> linux:102 (KEY_HOME) -> qcode:Q_KEY_CODE_HOME (home) */
	Q_KEY_CODE_LEFT,          /* win32:37 (VK_LEFT) -> linux:105 (KEY_LEFT) -> qcode:Q_KEY_CODE_LEFT (left) */
	Q_KEY_CODE_UP,            /* win32:38 (VK_UP) -> linux:103 (KEY_UP) -> qcode:Q_KEY_CODE_UP (up) */
	Q_KEY_CODE_RIGHT,         /* win32:39 (VK_RIGHT) -> linux:106 (KEY_RIGHT) -> qcode:Q_KEY_CODE_RIGHT (right) */
	Q_KEY_CODE_DOWN,          /* win32:40 (VK_DOWN) -> linux:108 (KEY_DOWN) -> qcode:Q_KEY_CODE_DOWN (down) */
	Q_KEY_CODE_UNMAPPED,      /* win32:41 (VK_SELECT) -> linux:353 (KEY_SELECT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:42 (VK_PRINT) -> linux:210 (KEY_PRINT) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:43 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_SYSRQ,         /* win32:44 (VK_SNAPSHOT) -> linux:99 (KEY_SYSRQ) -> qcode:Q_KEY_CODE_SYSRQ (sysrq) */
	Q_KEY_CODE_INSERT,        /* win32:45 (VK_INSERT) -> linux:110 (KEY_INSERT) -> qcode:Q_KEY_CODE_INSERT (insert) */
	Q_KEY_CODE_DELETE,        /* win32:46 (VK_DELETE) -> linux:111 (KEY_DELETE) -> qcode:Q_KEY_CODE_DELETE (delete) */
	Q_KEY_CODE_HELP,          /* win32:47 (VK_HELP) -> linux:138 (KEY_HELP) -> qcode:Q_KEY_CODE_HELP (help) */
	Q_KEY_CODE_0,             /* win32:48 (VK_0) -> linux:11 (KEY_0) -> qcode:Q_KEY_CODE_0 (0) */
	Q_KEY_CODE_1,             /* win32:49 (VK_1) -> linux:2 (KEY_1) -> qcode:Q_KEY_CODE_1 (1) */
	Q_KEY_CODE_2,             /* win32:50 (VK_2) -> linux:3 (KEY_2) -> qcode:Q_KEY_CODE_2 (2) */
	Q_KEY_CODE_3,             /* win32:51 (VK_3) -> linux:4 (KEY_3) -> qcode:Q_KEY_CODE_3 (3) */
	Q_KEY_CODE_4,             /* win32:52 (VK_4) -> linux:5 (KEY_4) -> qcode:Q_KEY_CODE_4 (4) */
	Q_KEY_CODE_5,             /* win32:53 (VK_5) -> linux:6 (KEY_5) -> qcode:Q_KEY_CODE_5 (5) */
	Q_KEY_CODE_6,             /* win32:54 (VK_6) -> linux:7 (KEY_6) -> qcode:Q_KEY_CODE_6 (6) */
	Q_KEY_CODE_7,             /* win32:55 (VK_7) -> linux:8 (KEY_7) -> qcode:Q_KEY_CODE_7 (7) */
	Q_KEY_CODE_8,             /* win32:56 (VK_8) -> linux:9 (KEY_8) -> qcode:Q_KEY_CODE_8 (8) */
	Q_KEY_CODE_9,             /* win32:57 (VK_9) -> linux:10 (KEY_9) -> qcode:Q_KEY_CODE_9 (9) */
	Q_KEY_CODE_UNMAPPED,      /* win32:58 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:59 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:60 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:61 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:62 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:63 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:64 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_A,             /* win32:65 (VK_A) -> linux:30 (KEY_A) -> qcode:Q_KEY_CODE_A (a) */
	Q_KEY_CODE_B,             /* win32:66 (VK_B) -> linux:48 (KEY_B) -> qcode:Q_KEY_CODE_B (b) */
	Q_KEY_CODE_C,             /* win32:67 (VK_C) -> linux:46 (KEY_C) -> qcode:Q_KEY_CODE_C (c) */
	Q_KEY_CODE_D,             /* win32:68 (VK_D) -> linux:32 (KEY_D) -> qcode:Q_KEY_CODE_D (d) */
	Q_KEY_CODE_E,             /* win32:69 (VK_E) -> linux:18 (KEY_E) -> qcode:Q_KEY_CODE_E (e) */
	Q_KEY_CODE_F,             /* win32:70 (VK_F) -> linux:33 (KEY_F) -> qcode:Q_KEY_CODE_F (f) */
	Q_KEY_CODE_G,             /* win32:71 (VK_G) -> linux:34 (KEY_G) -> qcode:Q_KEY_CODE_G (g) */
	Q_KEY_CODE_H,             /* win32:72 (VK_H) -> linux:35 (KEY_H) -> qcode:Q_KEY_CODE_H (h) */
	Q_KEY_CODE_I,             /* win32:73 (VK_I) -> linux:23 (KEY_I) -> qcode:Q_KEY_CODE_I (i) */
	Q_KEY_CODE_J,             /* win32:74 (VK_J) -> linux:36 (KEY_J) -> qcode:Q_KEY_CODE_J (j) */
	Q_KEY_CODE_K,             /* win32:75 (VK_K) -> linux:37 (KEY_K) -> qcode:Q_KEY_CODE_K (k) */
	Q_KEY_CODE_L,             /* win32:76 (VK_L) -> linux:38 (KEY_L) -> qcode:Q_KEY_CODE_L (l) */
	Q_KEY_CODE_M,             /* win32:77 (VK_M) -> linux:50 (KEY_M) -> qcode:Q_KEY_CODE_M (m) */
	Q_KEY_CODE_N,             /* win32:78 (VK_N) -> linux:49 (KEY_N) -> qcode:Q_KEY_CODE_N (n) */
	Q_KEY_CODE_O,             /* win32:79 (VK_O) -> linux:24 (KEY_O) -> qcode:Q_KEY_CODE_O (o) */
	Q_KEY_CODE_P,             /* win32:80 (VK_P) -> linux:25 (KEY_P) -> qcode:Q_KEY_CODE_P (p) */
	Q_KEY_CODE_Q,             /* win32:81 (VK_Q) -> linux:16 (KEY_Q) -> qcode:Q_KEY_CODE_Q (q) */
	Q_KEY_CODE_R,             /* win32:82 (VK_R) -> linux:19 (KEY_R) -> qcode:Q_KEY_CODE_R (r) */
	Q_KEY_CODE_S,             /* win32:83 (VK_S) -> linux:31 (KEY_S) -> qcode:Q_KEY_CODE_S (s) */
	Q_KEY_CODE_T,             /* win32:84 (VK_T) -> linux:20 (KEY_T) -> qcode:Q_KEY_CODE_T (t) */
	Q_KEY_CODE_U,             /* win32:85 (VK_U) -> linux:22 (KEY_U) -> qcode:Q_KEY_CODE_U (u) */
	Q_KEY_CODE_V,             /* win32:86 (VK_V) -> linux:47 (KEY_V) -> qcode:Q_KEY_CODE_V (v) */
	Q_KEY_CODE_W,             /* win32:87 (VK_W) -> linux:17 (KEY_W) -> qcode:Q_KEY_CODE_W (w) */
	Q_KEY_CODE_X,             /* win32:88 (VK_X) -> linux:45 (KEY_X) -> qcode:Q_KEY_CODE_X (x) */
	Q_KEY_CODE_Y,             /* win32:89 (VK_Y) -> linux:21 (KEY_Y) -> qcode:Q_KEY_CODE_Y (y) */
	Q_KEY_CODE_Z,             /* win32:90 (VK_Z) -> linux:44 (KEY_Z) -> qcode:Q_KEY_CODE_Z (z) */
	Q_KEY_CODE_META_L,        /* win32:91 (VK_LWIN) -> linux:125 (KEY_LEFTMETA) -> qcode:Q_KEY_CODE_META_L (meta_l) */
	Q_KEY_CODE_META_R,        /* win32:92 (VK_RWIN) -> linux:126 (KEY_RIGHTMETA) -> qcode:Q_KEY_CODE_META_R (meta_r) */
	Q_KEY_CODE_COMPOSE,       /* win32:93 (VK_APPS) -> linux:127 (KEY_COMPOSE) -> qcode:Q_KEY_CODE_COMPOSE (compose) */
	Q_KEY_CODE_UNMAPPED,      /* win32:94 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_SLEEP,         /* win32:95 (VK_SLEEP) -> linux:142 (KEY_SLEEP) -> qcode:Q_KEY_CODE_SLEEP (sleep) */
	Q_KEY_CODE_KP_0,          /* win32:96 (VK_NUMPAD0) -> linux:82 (KEY_KP0) -> qcode:Q_KEY_CODE_KP_0 (kp_0) */
	Q_KEY_CODE_KP_1,          /* win32:97 (VK_NUMPAD1) -> linux:79 (KEY_KP1) -> qcode:Q_KEY_CODE_KP_1 (kp_1) */
	Q_KEY_CODE_KP_2,          /* win32:98 (VK_NUMPAD2) -> linux:80 (KEY_KP2) -> qcode:Q_KEY_CODE_KP_2 (kp_2) */
	Q_KEY_CODE_KP_3,          /* win32:99 (VK_NUMPAD3) -> linux:81 (KEY_KP3) -> qcode:Q_KEY_CODE_KP_3 (kp_3) */
	Q_KEY_CODE_KP_4,          /* win32:100 (VK_NUMPAD4) -> linux:75 (KEY_KP4) -> qcode:Q_KEY_CODE_KP_4 (kp_4) */
	Q_KEY_CODE_KP_5,          /* win32:101 (VK_NUMPAD5) -> linux:76 (KEY_KP5) -> qcode:Q_KEY_CODE_KP_5 (kp_5) */
	Q_KEY_CODE_KP_6,          /* win32:102 (VK_NUMPAD6) -> linux:77 (KEY_KP6) -> qcode:Q_KEY_CODE_KP_6 (kp_6) */
	Q_KEY_CODE_KP_7,          /* win32:103 (VK_NUMPAD7) -> linux:71 (KEY_KP7) -> qcode:Q_KEY_CODE_KP_7 (kp_7) */
	Q_KEY_CODE_KP_8,          /* win32:104 (VK_NUMPAD8) -> linux:72 (KEY_KP8) -> qcode:Q_KEY_CODE_KP_8 (kp_8) */
	Q_KEY_CODE_KP_9,          /* win32:105 (VK_NUMPAD9) -> linux:73 (KEY_KP9) -> qcode:Q_KEY_CODE_KP_9 (kp_9) */
	Q_KEY_CODE_KP_MULTIPLY,   /* win32:106 (VK_MULTIPLY) -> linux:55 (KEY_KPASTERISK) -> qcode:Q_KEY_CODE_KP_MULTIPLY (kp_multiply) */
	Q_KEY_CODE_KP_ADD,        /* win32:107 (VK_ADD) -> linux:78 (KEY_KPPLUS) -> qcode:Q_KEY_CODE_KP_ADD (kp_add) */
	Q_KEY_CODE_KP_COMMA,      /* win32:108 (VK_SEPARATOR??) -> linux:121 (KEY_KPCOMMA) -> qcode:Q_KEY_CODE_KP_COMMA (kp_comma) */
	Q_KEY_CODE_KP_SUBTRACT,   /* win32:109 (VK_SUBTRACT) -> linux:74 (KEY_KPMINUS) -> qcode:Q_KEY_CODE_KP_SUBTRACT (kp_subtract) */
	Q_KEY_CODE_KP_DECIMAL,    /* win32:110 (VK_DECIMAL) -> linux:83 (KEY_KPDOT) -> qcode:Q_KEY_CODE_KP_DECIMAL (kp_decimal) */
	Q_KEY_CODE_KP_DIVIDE,     /* win32:111 (VK_DIVIDE) -> linux:98 (KEY_KPSLASH) -> qcode:Q_KEY_CODE_KP_DIVIDE (kp_divide) */
	Q_KEY_CODE_F1,            /* win32:112 (VK_F1) -> linux:59 (KEY_F1) -> qcode:Q_KEY_CODE_F1 (f1) */
	Q_KEY_CODE_F2,            /* win32:113 (VK_F2) -> linux:60 (KEY_F2) -> qcode:Q_KEY_CODE_F2 (f2) */
	Q_KEY_CODE_F3,            /* win32:114 (VK_F3) -> linux:61 (KEY_F3) -> qcode:Q_KEY_CODE_F3 (f3) */
	Q_KEY_CODE_F4,            /* win32:115 (VK_F4) -> linux:62 (KEY_F4) -> qcode:Q_KEY_CODE_F4 (f4) */
	Q_KEY_CODE_F5,            /* win32:116 (VK_F5) -> linux:63 (KEY_F5) -> qcode:Q_KEY_CODE_F5 (f5) */
	Q_KEY_CODE_F6,            /* win32:117 (VK_F6) -> linux:64 (KEY_F6) -> qcode:Q_KEY_CODE_F6 (f6) */
	Q_KEY_CODE_F7,            /* win32:118 (VK_F7) -> linux:65 (KEY_F7) -> qcode:Q_KEY_CODE_F7 (f7) */
	Q_KEY_CODE_F8,            /* win32:119 (VK_F8) -> linux:66 (KEY_F8) -> qcode:Q_KEY_CODE_F8 (f8) */
	Q_KEY_CODE_F9,            /* win32:120 (VK_F9) -> linux:67 (KEY_F9) -> qcode:Q_KEY_CODE_F9 (f9) */
	Q_KEY_CODE_F10,           /* win32:121 (VK_F10) -> linux:68 (KEY_F10) -> qcode:Q_KEY_CODE_F10 (f10) */
	Q_KEY_CODE_F11,           /* win32:122 (VK_F11) -> linux:87 (KEY_F11) -> qcode:Q_KEY_CODE_F11 (f11) */
	Q_KEY_CODE_F12,           /* win32:123 (VK_F12) -> linux:88 (KEY_F12) -> qcode:Q_KEY_CODE_F12 (f12) */
	Q_KEY_CODE_UNMAPPED,      /* win32:124 (VK_F13) -> linux:183 (KEY_F13) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:125 (VK_F14) -> linux:184 (KEY_F14) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:126 (VK_F15) -> linux:185 (KEY_F15) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:127 (VK_F16) -> linux:186 (KEY_F16) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:128 (VK_F17) -> linux:187 (KEY_F17) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:129 (VK_F18) -> linux:188 (KEY_F18) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:130 (VK_F19) -> linux:189 (KEY_F19) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:131 (VK_F20) -> linux:190 (KEY_F20) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:132 (VK_F21) -> linux:191 (KEY_F21) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:133 (VK_F22) -> linux:192 (KEY_F22) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:134 (VK_F23) -> linux:193 (KEY_F23) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:135 (VK_F24) -> linux:194 (KEY_F24) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:136 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:137 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:138 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:139 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:140 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:141 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:142 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:143 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_NUM_LOCK,      /* win32:144 (VK_NUMLOCK) -> linux:69 (KEY_NUMLOCK) -> qcode:Q_KEY_CODE_NUM_LOCK (num_lock) */
	Q_KEY_CODE_SCROLL_LOCK,   /* win32:145 (VK_SCROLL) -> linux:70 (KEY_SCROLLLOCK) -> qcode:Q_KEY_CODE_SCROLL_LOCK (scroll_lock) */
	Q_KEY_CODE_UNMAPPED,      /* win32:146 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:147 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:148 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:149 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:150 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:151 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:152 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:153 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:154 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:155 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:156 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:157 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:158 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:159 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_SHIFT,         /* win32:160 (VK_LSHIFT) -> linux:42 (KEY_LEFTSHIFT) -> qcode:Q_KEY_CODE_SHIFT (shift) */
	Q_KEY_CODE_SHIFT_R,       /* win32:161 (VK_RSHIFT) -> linux:54 (KEY_RIGHTSHIFT) -> qcode:Q_KEY_CODE_SHIFT_R (shift_r) */
	Q_KEY_CODE_CTRL,          /* win32:162 (VK_CONTROL) -> linux:29 (KEY_LEFTCTRL) -> qcode:Q_KEY_CODE_CTRL (ctrl) */
	Q_KEY_CODE_CTRL_R,        /* win32:163 (VK_RCONTROL) -> linux:97 (KEY_RIGHTCTRL) -> qcode:Q_KEY_CODE_CTRL_R (ctrl_r) */
	Q_KEY_CODE_ALT,           /* win32:164 (VK_MENU) -> linux:56 (KEY_LEFTALT) -> qcode:Q_KEY_CODE_ALT (alt) */
	Q_KEY_CODE_ALT_R,         /* win32:165 (VK_RMENU) -> linux:100 (KEY_RIGHTALT) -> qcode:Q_KEY_CODE_ALT_R (alt_r) */
	Q_KEY_CODE_AC_BACK,       /* win32:166 (VK_BROWSER_BACK) -> linux:158 (KEY_BACK) -> qcode:Q_KEY_CODE_AC_BACK (ac_back) */
	Q_KEY_CODE_AC_FORWARD,    /* win32:167 (VK_BROWSER_FORWARD) -> linux:159 (KEY_FORWARD) -> qcode:Q_KEY_CODE_AC_FORWARD (ac_forward) */
	Q_KEY_CODE_AC_REFRESH,    /* win32:168 (VK_BROWSER_REFRESH) -> linux:173 (KEY_REFRESH) -> qcode:Q_KEY_CODE_AC_REFRESH (ac_refresh) */
	Q_KEY_CODE_STOP,          /* win32:169 (VK_BROWSER_STOP) -> linux:128 (KEY_STOP) -> qcode:Q_KEY_CODE_STOP (stop) */
	Q_KEY_CODE_UNMAPPED,      /* win32:170 (VK_BROWSER_SEARCH) -> linux:217 (KEY_SEARCH) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:171 (VK_BROWSER_FAVOURITES) -> linux:364 (KEY_FAVORITES) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_AC_HOME,       /* win32:172 (VK_BROWSER_HOME) -> linux:172 (KEY_HOMEPAGE) -> qcode:Q_KEY_CODE_AC_HOME (ac_home) */
	Q_KEY_CODE_AUDIOMUTE,     /* win32:173 (VK_VOLUME_MUTE) -> linux:113 (KEY_MUTE) -> qcode:Q_KEY_CODE_AUDIOMUTE (audiomute) */
	Q_KEY_CODE_VOLUMEDOWN,    /* win32:174 (VK_VOLUME_DOWN) -> linux:114 (KEY_VOLUMEDOWN) -> qcode:Q_KEY_CODE_VOLUMEDOWN (volumedown) */
	Q_KEY_CODE_VOLUMEUP,      /* win32:175 (VK_VOLUME_UP) -> linux:115 (KEY_VOLUMEUP) -> qcode:Q_KEY_CODE_VOLUMEUP (volumeup) */
	Q_KEY_CODE_AUDIONEXT,     /* win32:176 (VK_MEDIA_NEXT_TRACK) -> linux:163 (KEY_NEXTSONG) -> qcode:Q_KEY_CODE_AUDIONEXT (audionext) */
	Q_KEY_CODE_AUDIOPREV,     /* win32:177 (VK_MEDIA_PREV_TRACK) -> linux:165 (KEY_PREVIOUSSONG) -> qcode:Q_KEY_CODE_AUDIOPREV (audioprev) */
	Q_KEY_CODE_AUDIOSTOP,     /* win32:178 (VK_MEDIA_STOP) -> linux:166 (KEY_STOPCD) -> qcode:Q_KEY_CODE_AUDIOSTOP (audiostop) */
	Q_KEY_CODE_AUDIOPLAY,     /* win32:179 (VK_MEDIA_PLAY_PAUSE) -> linux:164 (KEY_PLAYPAUSE) -> qcode:Q_KEY_CODE_AUDIOPLAY (audioplay) */
	Q_KEY_CODE_UNMAPPED,      /* win32:180 (VK_LAUNCH_MAIL) -> linux:215 (KEY_EMAIL) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:181 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:182 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:183 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:184 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:185 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_SEMICOLON,     /* win32:186 (VK_OEM_1) -> linux:39 (KEY_SEMICOLON) -> qcode:Q_KEY_CODE_SEMICOLON (semicolon) */
	Q_KEY_CODE_EQUAL,         /* win32:187 (VK_OEM_PLUS) -> linux:13 (KEY_EQUAL) -> qcode:Q_KEY_CODE_EQUAL (equal) */
	Q_KEY_CODE_COMMA,         /* win32:188 (VK_OEM_COMMA) -> linux:51 (KEY_COMMA) -> qcode:Q_KEY_CODE_COMMA (comma) */
	Q_KEY_CODE_MINUS,         /* win32:189 (VK_OEM_MINUS) -> linux:12 (KEY_MINUS) -> qcode:Q_KEY_CODE_MINUS (minus) */
	Q_KEY_CODE_DOT,           /* win32:190 (VK_OEM_PERIOD) -> linux:52 (KEY_DOT) -> qcode:Q_KEY_CODE_DOT (dot) */
	Q_KEY_CODE_SLASH,         /* win32:191 (VK_OEM_2) -> linux:53 (KEY_SLASH) -> qcode:Q_KEY_CODE_SLASH (slash) */
	Q_KEY_CODE_GRAVE_ACCENT,  /* win32:192 (VK_OEM_3) -> linux:41 (KEY_GRAVE) -> qcode:Q_KEY_CODE_GRAVE_ACCENT (grave_accent) */
	Q_KEY_CODE_UNMAPPED,      /* win32:193 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:194 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:195 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:196 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:197 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:198 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:199 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:200 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:201 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:202 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:203 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:204 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:205 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:206 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:207 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:208 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:209 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:210 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:211 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:212 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:213 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:214 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:215 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:216 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:217 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:218 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_BRACKET_LEFT,  /* win32:219 (VK_OEM_4) -> linux:26 (KEY_LEFTBRACE) -> qcode:Q_KEY_CODE_BRACKET_LEFT (bracket_left) */
	Q_KEY_CODE_BACKSLASH,     /* win32:220 (VK_OEM_5) -> linux:43 (KEY_BACKSLASH) -> qcode:Q_KEY_CODE_BACKSLASH (backslash) */
	Q_KEY_CODE_BRACKET_RIGHT, /* win32:221 (VK_OEM_6) -> linux:27 (KEY_RIGHTBRACE) -> qcode:Q_KEY_CODE_BRACKET_RIGHT (bracket_right) */
	Q_KEY_CODE_APOSTROPHE,    /* win32:222 (VK_OEM_7) -> linux:40 (KEY_APOSTROPHE) -> qcode:Q_KEY_CODE_APOSTROPHE (apostrophe) */
	Q_KEY_CODE_UNMAPPED,      /* win32:223 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:224 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_LESS,          /* win32:225 (VK_OEM_102) -> linux:86 (KEY_102ND) -> qcode:Q_KEY_CODE_LESS (less) */
	Q_KEY_CODE_UNMAPPED,      /* win32:226 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:227 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:228 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:229 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:230 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:231 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:232 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:233 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:234 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:235 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:236 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:237 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:238 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:239 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:240 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:241 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:242 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:243 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:244 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:245 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:246 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:247 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:248 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:249 (unnamed) -> linux:None (unnamed) -> qcode:None (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:250 (VK_PLAY) -> linux:207 (KEY_PLAY) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
	Q_KEY_CODE_UNMAPPED,      /* win32:251 (VK_ZOOM) -> linux:372 (KEY_ZOOM) -> qcode:Q_KEY_CODE_UNMAPPED (unnamed) */
};
