#define ID_DIALOG_GOTOADDR 205
#define ID_EDIT_GOTOADDR   206

#define ID_DIALOG_GOTOLABEL  215
#define ID_EDIT_GOTOLABEL 216
#define ID_BUTTON_GOTOLABEL 217
#define ID_RADIO1_GOTOLABEL 218
#define ID_RADIO2_GOTOLABEL 219
#define ID_TAB_GOTOLABEL 220
#define ID_LISTBOX_GOTOLABEL 221

#define ID_DIALOG_FIND 225

#define ID_DIALOG_EDITREGS 235

#define ID_DIALOG_PROGRESS 245
#define ID_STATIC_PROGRESS 246
#define ID_PROGRESSBAR_PROGRESS 247

#define ID_DIALOG_SETDATATYPES 255

#define ID_DIALOG_PLACESTRUCT 265
#define ID_COMBO_PLACESTRUCT 266
#define ID_EDIT1_PLACESTRUCT 267
#define ID_EDIT2_PLACESTRUCT 268
