//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GSdx.rc
//
#define IDC_PALTEX                      2001
#define IDC_LOGZ                        2002
#define IDC_CODECS                      2003
#define IDC_RESOLUTION                  2004
#define IDC_RESX_EDIT                   2005
#define IDC_RESY_EDIT                   2006
#define IDC_AA1                         2007
#define IDC_SWTHREADS_TEXT              2008
#define IDC_SWTHREADS                   2009
#define IDC_SWTHREADS_EDIT              2010
#define IDC_FILTER_TEXT                 2011
#define IDC_FILTER                      2012
#define IDC_DITHERING                   2013
#define IDC_RESX                        2014
#define IDC_RESY                        2015
#define IDD_CONFIG                      2016
#define IDB_LOGO9                       2017
#define IDB_LOGO10                      2018
#define IDB_LOGO11                      2019
#define IDB_LOGOGL                      2020
#define IDB_NULL                        2021
#define IDB_PSX_LOGO9                   2022
#define IDB_PSX_LOGO11                  2023
#define IDB_PSX_NULL                    2024
#define IDC_FBA                         2025
#define IDC_LOGO9                       2026
#define IDC_LOGO10                      2027
#define IDC_LOGO11                      2028
#define IDC_LOGOGL                      2029
#define IDC_NULL                        2030
#define IDC_PSX_LOGO9                   2031
#define IDC_PSX_LOGO11                  2032
#define IDC_PSX_NULL                    2033
#define IDD_CAPTURE                     2034
#define IDD_GPUCONFIG                   2035
#define IDC_RENDERER                    2036
#define IDC_INTERLACE                   2037
#define IDC_ASPECTRATIO                 2038
#define IDC_ALPHAHACK                   2039
#define IDC_SCALE                       2040
#define IDC_UPSCALE_MULTIPLIER          2041
#define IDC_BROWSE                      2042
#define IDC_OFFSETHACK                  2043
#define IDC_OFFSETHACK_TEXT             2044
#define IDC_FILENAME                    2045
#define IDC_SKIPDRAWHACK                2046
#define IDC_WIDTH                       2047
#define IDC_HEIGHT                      2048
#define IDC_CONFIGURE                   2049
#define IDC_ACCURATE_BLEND_UNIT_TEXT    2050
#define IDC_WINDOWED                    2051
#define IDC_SKIPDRAWHACKEDIT            2052
#define IDC_SPRITEHACK                  2053
#define IDC_SPRITEHACK_TEXT             2054
#define IDC_SATURATION_SLIDER           2055
#define IDC_BRIGHTNESS_SLIDER           2056
#define IDC_CONTRAST_SLIDER             2057
#define IDC_SHADEBUTTON                 2058
#define IDC_SHADEBOOST                  2059
#define IDC_HACKS_ENABLED               2060
#define IDC_SATURATION_TEXT             2061
#define IDC_BRIGHTNESS_TEXT             2062
#define IDC_CONTRAST_TEXT               2063
#define IDC_MSAACB                      2064
#define IDC_MSAA_TEXT                   2065
#define IDC_HACKSBUTTON                 2066
#define IDC_WILDHACK                    2067
#define IDC_CHECK_DISABLE_ALL_HACKS     2068
#define IDC_ALPHASTENCIL                2069
#define IDC_ADAPTER                     2070
#define IDC_TCOFFSETX                   2071
#define IDC_TCOFFSETX2                  2072
#define IDC_TCOFFSETY                   2073
#define IDC_TCOFFSETY2                  2074
#define IDC_FXAA                        2075
#define IDC_SHADER_FX                   2076
#define IDC_AFCOMBO_TEXT                2077
#define IDC_AFCOMBO                     2078
#define IDC_OPENCL_DEVICE               2079
#define IDC_OPENCL_TEXT                 2080
#define IDC_ACCURATE_BLEND_UNIT         2081
#define IDC_ACCURATE_DATE               2082
#define IDC_ROUND_SPRITE                2083
#define IDC_ROUND_SPRITE_TEXT           2084
#define IDC_ALIGN_SPRITE                2085
#define IDC_CRC_LEVEL                   2086
#define IDC_CRC_LEVEL_TEXT              2087
#define IDC_TC_DEPTH                    2088
#define IDC_COLORSPACE                  2089
#define IDC_SHADER_FX_EDIT              2090
#define IDC_SHADER_FX_CONF_EDIT         2091
#define IDC_SHADER_FX_BUTTON            2092
#define IDC_SHADER_FX_CONF_BUTTON       2093
#define IDC_SHADER_FX_TEXT              2094
#define IDC_SHADER_FX_CONF_TEXT         2095
#define IDC_CUSTOM_TEXT                 2096
#define IDC_UPSCALE_MULTIPLIER_TEXT     2097
#define IDC_MIPMAP_HW                   2098
#define IDC_MIPMAP_HW_TEXT              2099
#define IDC_MIPMAP_SW                   2100
#define IDC_PRELOAD_GS                  2101
#define IDC_TVSHADER                    2102
#define IDC_FAST_TC_INV                 2103
#define IDC_LARGE_FB                    2104
#define IDC_AUTO_FLUSH                  2105
#define IDC_UNSCALE_POINT_LINE          2106
#define IDC_OSD_FONT_EDIT               2107
#define IDC_OSD_FONT_BUTTON             2108
#define IDC_OSD_SPEED                   2109
#define IDC_OSD_SPEED_EDIT              2110
#define IDC_OSD_SIZE                    2111
#define IDC_OSD_SIZE_EDIT               2112
#define IDC_OSD_TRANSPARENCY_SLIDER     2113
#define IDC_OSD_TRANSPARENCY_TEXT       2114
#define IDC_OSD_LOG                     2115
#define IDC_OSD_MONITOR                 2116
#define IDC_OSD_INDICATOR               2117
#define IDC_OSDBUTTON                   2118
#define IDC_OSD_MAX_LOG                 2119
#define IDC_OSD_MAX_LOG_EDIT            2120
#define IDR_CONVERT_FX                  10000
#define IDR_TFX_FX                      10001
#define IDR_MERGE_FX                    10002
#define IDR_INTERLACE_FX                10003
#define IDR_FXAA_FX                     10004
#define IDR_CS_FX                       10005
#define IDD_SHADER                      10006
#define IDR_SHADEBOOST_FX               10007
#define IDR_TFX_CL                      10008
#define IDD_HACKS                       10009
#define IDD_OSD                         10010
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10013
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2121
#define _APS_NEXT_SYMED_VALUE           5000
#endif
#endif
