# Docs - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Emulation Bug Report
description: Problem in a game (ie. graphical artifacts, crashes)? Help us improve it.
title: "[BUG]: "
labels: [Bug]
# assignees:
#   - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Important: Read First

        Please do not make support requests on GitHub. Our issue tracker is for tracking bugs and feature requests only
        If you need help configuring the emulator please make a request on our forums or contact us on discord.

        If you are unsure, start with [discord](https://discord.com/invite/TCz3t9k) or the [forums](https://forums.pcsx2.net/index.php).

        Please make an effort to make sure your issue isn't already reported.

        Please make sure your game is verified using the built-in game verifier.

        Do not create issues involving software piracy of BIOS or ISO files, our rules specifically prohibit this and your issue will be closed.

        ### Please Avoid Issues Pertaining to the Following:
        - We are **not** accepting bug reports for **PSX mode** at this time.
          - If you are interested in helping contribute to PSX mode please do so on the forums. Otherwise our recommendation is that you use  [Duckstation](https://github.com/stenzek/duckstation/releases/tag/latest).
        - We do **not** accept issues relating to **upscaling** at this time.
          - We are aware of the various problems with upscaling. The issue spans many games and having hundreds of issues for the same fundamental issues isn't particularly helpful. There are several workarounds for graphical problems that come as a result of upscaling.
          - Please try your game at native resolution before creating an issue.
          - If your bug is the result of upscaling please use the forums or discord for assistance with various upscaling workarounds. Additionally, the unofficial PCSX2 [Wiki](https://wiki.pcsx2.net/Main_Page) often lists various fixes for upscaling issues.
        - We do **not** accept issues relating to Widescreen/no-interlace patches at this time.
          - Any issues pertaining to Widescreen/no-interlace patches please forward them to the [patches repository](https://github.com/PCSX2/pcsx2_patches). 
        - We do **not** accept issues pertaining to Linux builds other than the official AppImage and Flatpak.
          - Please contact your packager for support. We have no control over other builds, nor can we investigate any issues, and historically they have been known to be broken.
          - This includes pre-configured "distributions" such as EmuDeck, the "AUR", etc.

  - type: textarea
    id: desc
    attributes:
      label: Describe the Bug
      description: "A clear and concise description of what the bug is"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: "Steps to reproduce the behavior"
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen"
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## System Info

        Please make sure your system meets our requirements for OS version, CPU and GPU
        - [System Requirements](https://github.com/PCSX2/pcsx2#system-requirements).

        Performance issues as a result of not meeting our hardware requirements are not valid.

        We are **not** accepting issues related to the **libretro** core. The libretro core is being maintained separately at this time
  - type: input
    id: rev
    attributes:
      label: PCSX2 Revision
      description: "We only accept bug reports for the latest dev version. Please try upgrading before making an issue."
      placeholder: "Example: v1.7.1337"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
      - Windows 11
      - Windows 10 (64bit)
      - Linux (64bit) - Specify distro below
      - macOS 14 (Sonoma)
      - macOS 13 (Ventura)
      - macOS 12 (Monterey)
      - macOS 11 (Big Sur)
    validations:
      required: true
  - type: input
    id: os-distro
    attributes:
      label: If Linux - Specify Distro
      placeholder: "Example: Arch"
    validations:
      required: false
  - type: input
    id: cpu
    attributes:
      label: CPU
      placeholder: "Example: i5-7600"
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: GPU
      placeholder: "Example: GTX 1070"
    validations:
      required: true
  - type: textarea
    id: gsSettings
    attributes:
      label: GS Settings
      description: "Any **non-default** settings for GS. If you don't want to list them out, please provide screenshots of your configuration window (including hw hacks if enabled)."
    validations:
      required: false
  - type: textarea
    id: emuSettings
    attributes:
      label: Emulation Settings
      description: |
        Any non-default core settings. If you don't want to list them out, please provide screenshots of your configuration window.

        Please note that defaults tend to work best.

        If you need to modify the settings manually to fix an issue , please state that explicitly.
    validations:
      required: false
  - type: textarea
    id: gsScreens
    attributes:
      label: GS Window Screenshots
      description: "If your issue is graphical in nature and you think screenshots will help illustrate your issue, you may do that here."
    validations:
      required: false
  - type: textarea
    id: logsDumps
    attributes:
      label: "Logs & Dumps"
      description: |
        Please feel free to attach any logs, block dumps, GSdump, etc here.
        If PCSX2 crashed, please post crash logs and the .dmp file (in a zip file) if appropriate.
        If your problem is graphical in nature it is highly recommended that you provide a GSdump. [GSdump Guide](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump)
    validations:
      required: false
