name: 🐧 Linux aarch64 Builds

on:
  push:
    branches-ignore:
      - "l10n_master"
  pull_request:
    branches:
      - master

jobs:
  build_linux_qt:
    name: "AppImage"
    uses: ./.github/workflows/linux_build_qt.yml
    with:
      jobName: "AppImage Build"
      artifactPrefixName: "PCSX2-linux-Qt-arm64-appimage"
      compiler: clang
      cmakeflags: ""
      buildAppImage: true
    secrets: inherit
