name: 🖥️ Windows Builds

on:
  push:
    branches:
      - "macOS"
  pull_request:
    branches:
      - macOS

jobs:
  build_windows_qt_arm64:
    name: "arm64"
    uses: ./.github/workflows/windows_build_qt.yml
    with:
      jobName: "Windows arm64 Build"
      artifactPrefixName: "ARMSX2-windows-Qt-arm64"
    secrets: inherit
